connection:
  host: 'irc.twitch.tv'
  port: 6667
  oauth: 'oauth:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  username: 'gRuFtBoT'
  channel: '#gruftbot'
  owner: 'grufty'

database:
  connection: 'sqlite:///path/to/database.db'

logging:
  timestamp: '%H:%M:%S'
  timestampPre: '<'
  timestampSuf: '>'
  general: true
  messages: true
  joins: true
  op: true

